#!/bin/bash

sudo pacman -Sy --noconfirm --needed ruby
[ "$(command -v bundler)" ] || gem install bundler

cd "$(dirname "$(readlink -f "$0")")"
[ -d .bundle ] || bundle install --path=.bundle

unitdir=/usr/lib/systemd/system
mkdir -p "$unitdir"

sudo tee "$unitdir"/lycoris@.service <<EOF
[Unit]
Description=Lycoris -- A Twitter bot using Markov chains.

[Service]
ExecStart=/bin/sh -c 'cd ~/${PWD#/home/*/}; exec ./lycoris.rb'
Restart=on-failure
RestartSec=60
User=%i
Group=%i

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl --now enable lycoris@"$(whoami)".service
